---
title: "DevDataProd_Week2"
author: "pduchesne"
date: "24 November 2017"
output: 
  html_document: 
    keep_md: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week 2 Assignment

A web page using R Markdown that features a map created with Leaflet.

```{r buildup, include=FALSE}

set.seed=(29092015)
#setwd("D:/Coursera/09-Developing Data Products/Week2")
library (leaflet)
library(rvest)
library(stringr)

# set URL for scraping of web page for airports & coordinates
url <- "https://en.wikipedia.org/wiki/List_of_airports_in_Luxembourg"

my_html <- read_html(url)
my_tables <- html_nodes(my_html,"table")[[1]]
airport_table <- html_table(my_tables)

#prepare data to exploit
separator<-gregexpr(";",airport_table[,5])
pos<-separator[[1]][1]
latfirst<-pos-8
latlast<-pos-1
lngfirst<-pos+2
lnglast<-pos+8

#pull usable coordinates from table
lat<-as.numeric(str_sub(airport_table[,5], latfirst, latlast))
lng<-as.numeric(str_sub(airport_table[,5], lngfirst, lnglast))
#pull airport names for popup
popup<-airport_table[,4]
df_points<-data.frame(lat,lng)
names(df_points) <- c("lat","lng")

#load customized icon
AirportIcon <- makeIcon (
        iconUrl = "airport5.png",
        iconWidth = 31*215/230, iconHeight = 31,
        iconAnchorX = 31*215/230/2, iconAnchorY = 16
)
```

## Map of the Grand Duchy of Luxembourg's Airports & Heliports


```{r map, echo=FALSE}
df_points %>% leaflet() %>%
        addTiles() %>%
        addMarkers(icon = AirportIcon, popup = popup)
```

